name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: esitieto
          tags: staging ${{ github.sha }}
          containerfiles: |
            ./frontend/Dockefile
          build-args: |
            BASE_PATH=/frontend
            STAGING=true

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/kurssiesitieto_ohtu/kurssiesitieto
          username: kurssiesitieto_ohtu+robotti
          password: ${{ secrets.QUAY_IO_TOKEN }}
