name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kurssiesitieto
          tags: staging ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            STAGING=true

#      - name: Build Image
#       run: docker build -t kurssiesitieto:staging .
#       working-directory: ./frontend

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: quay.io/kurssiesitieto_ohtu
          image: kurssiesitieto
          tags: staging
          username: kurssiesitieto_ohtu+robotti
          password: ${{ secrets.QUAY_IO_TOKEN }}
