# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test

on: [workflow_call, push]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3


    - name: Install Frontend Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Run Frontend Tests
      run: npx jest --coverage
      working-directory: ./frontend
    
  
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
    
    - name: Install Backend Dependencies
      run: npm install
      working-directory: ./backend
    
    - name: Run Backend Tests
      run: npm test
      working-directory: ./backend
