# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test

on: workflow_call

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4

    - name: Install Frontend Dependencies
      run: npm install

    - name: Run Frontend Tests
      run: npm run coverage:frontend
    
    - name: Upload frontend coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        token: ${{ secrets.COVERAGE_TOKEN }}
        slug: Kurssiesitieto/kurssiesitieto-ohtuprojekti

  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
    
    - name: Install Backend Dependencies
      run: npm install
    
    - name: Run Backend Tests
      run: npm run coverage:backend

    - name: Upload backend coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        token: ${{ secrets.COVERAGE_TOKEN }}
        slug: Kurssiesitieto/kurssiesitieto-ohtuprojekti

  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint
      

    

